/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Jni */

#ifndef _Included_jni_Jni
#define _Included_jni_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Jni
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jni_Jni_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jni_Jni
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jni_Jni_multiply{
   printf("¡Hola desde la DLL!\n");
}
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
